site_name: LTI 1.3 PHP framework
site_url: https://oat-sa.github.io/doc-lti1p3/

docs_dir: 'docs'

theme:
  name: material
  palette:
    scheme: slate
    logo: assets/logo.png
    favicon: assets/favicon.png
    features:
      - navigation.instant
      - navigation.tracking
      - navigation.sections
      - navigation.expand

nav:
  - About: 'docs/index.md'
  - IMS certifications: 'docs/certifications.md'
  - Repositories:
      - 'PHP libraries': 'docs/repositories/libraries.md'
      - 'Symfony bundle': 'docs/repositories/sfbundle.md'
  - DevKit: 'docs/devkit.md'
