site_name: LTI 1.3 PHP framework
site_url: https://oat-sa.github.io/doc-lti1p3/

repo_url: https://github.com/oat-sa?q=lti1p

theme:
  name: material
  palette:
    scheme: slate
    logo: 'assets/logo.png'
    favicon: 'assets/favicon.png'
    features:
      - navigation.instant
      - navigation.tracking
      - navigation.sections
      - navigation.expand

nav:
  - About: 'index.md'
  - IMS certifications: 'certifications.md'
  - Repositories:
      - 'PHP libraries': 'repositories/libraries.md'
      - 'Symfony bundle': 'repositories/sfbundle.md'
  - DevKit: 'devkit.md'
