site_name: LTI 1.3 PHP framework
site_url: https://oat-sa.github.io/doc-lti1p3/

repo_url: https://github.com/oat-sa?q=lti1p

theme:
  name: material
  palette:
    scheme: slate
    logo: 'assets/images/logo.png'
    favicon: 'assets/images/favicon.png'
    features:
      - navigation.instant
      - navigation.tracking
      - navigation.sections
      - navigation.expand

nav:
  - Overview: 'index.md'
  - IMS:
    - 'Certifications': 'ims/certifications.md'
    - 'Specifications': 'ims/specifications.md'
  - 'LTI 1.3 PHP libraries':
    - 'Core library':
      - 'Overview': 'libraries/lib-lti1p3-core/README.md'
      - 'Quick start':
        - 'Configuration': 'libraries/lib-lti1p3-core/doc/quickstart/configuration.md'
        - 'Interfaces': 'libraries/lib-lti1p3-core/doc/quickstart/interfaces.md'
        - 'JWKS': 'libraries/lib-lti1p3-core/doc/quickstart/jwks.md'
    - 'AGS library': 'libraries/lib-lti1p3-ags/README.md'
    - 'Basic outcome library': 'libraries/lib-lti1p3-basic-outcome/README.md'
    - 'Deep linking library': 'libraries/lib-lti1p3-deep-linking/README.md'
    - 'NRPS library': 'libraries/lib-lti1p3-nrps/README.md'
    - 'Proctoring library': 'libraries/lib-lti1p3-proctoring/README.md'
  - 'LTI 1.3 Symfony bundle': 'symfony_bundle.md'
  - 'LTI 1.3 DevKit': 'devkit.md'
